print("         Receipt         ")
print("     Hello World Shop    ")
print("-------------------------")
print("Product A     x1  :   200")
print("Product B     x2  :   250")
print("Product C     x1  :   350")
print("Product D     x7  :   450")
print("Product E     x4  :   650")
print("Product F     x5  :   750")
print("Product G     x3  :   850")
print("Product H     x2  :   950")
print("-------------------------")
print("Total             : 4,450")